name: Pull Request Action

on:
  push:
    branches:
      - build/beta

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          gh pr create \
            -B main \
            -H build/beta \
            --title 'Merge build/beta into main' \
            --body 'Created by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_REPO_TOKEN }}
      
      - name: Handle Errors
        if: ${{ failure() }}
        run: echo "Error occurred during pull request creation"

      - name: Send Notification
        if: ${{ always() }}
        run: echo "Pull request creation completed successfully"
