name: Create Pull Request from build/beta to main

on:
  push:
    branches:
      - build/beta

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MY_REPO_TOKEN }}
          branch: main
          title: pull request
          commit-message: |
            the first line is the commit message

            the commit description starts
            after a blank line and can be
            multiple lines
          committer: itkindom.dhomes@gmail.com
