name: Create Pull Request from build/beta to main

on:
  push:
    branches:
      - build/beta

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MY_REPO_TOKEN }}
          branch: main
          title: pull request
