name: Create Pull Request on Commit to build/beta

on:
  push:
    branches:
      - build/beta

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message and changed files
        id: commit_changes
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "::set-output name=message::${COMMIT_MESSAGE}"
          echo "::set-output name=files::${CHANGED_FILES}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MY_REPO_TOKEN }}
          commit-message: ${{ steps.commit_changes.outputs.message }}
          body: |
            List of changed files:
            ${{ steps.commit_changes.outputs.files }}
          branch: main
