name: Create Open Pull Request on Commit to build/beta

on:
  push:
    branches:
      - build/beta

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request with GitHub Script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_REPO_TOKEN }}
          script: |
            const { octokit } = require("@octokit/rest");

            const github = new octokit({ auth: githubToken });

            const title = steps.commit_changes.outputs.message;
            const body = "List of changed files:\n${{ steps.commit_changes.outputs.files }}";
            const head = "build/beta";
            const base = "main";

            await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              head,
              base,
            });
